using Microsoft.EntityFrameworkCore;

namespace CvApi.Tracking;

// Visitor tracking data (docs/VISITOR_SESSION_TRACKING.md). Lives in its own database file
// (/data/tracking.db), separate from app.db, so it can be created, migrated and purged independently.

/// <summary>One browser/device, identified by the cv_vid cookie (only after consent).</summary>
public sealed class Visitor
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public required string TenantId { get; set; }
    /// <summary>Probable person (§3.2, R3.10): same cookie, or matching fingerprint on the same network.</summary>
    public Guid PersonId { get; set; }
    /// <summary>How the person was linked: "cookie" (new person) or "fingerprint".</summary>
    public string PersonReason { get; set; } = "cookie";
    public DateTimeOffset FirstSeen { get; set; }
    public DateTimeOffset LastSeen { get; set; }
    public string? Device { get; set; }
    public string? Browser { get; set; }
    public string? Os { get; set; }
    public string? Language { get; set; }
    public int? TzOffset { get; set; }
}

/// <summary>A probable person; <see cref="LastSeen"/> drives the sliding retention (R9.2).</summary>
public sealed class Person
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public required string TenantId { get; set; }
    public DateTimeOffset FirstSeen { get; set; }
    public DateTimeOffset LastSeen { get; set; }
}

/// <summary>A contiguous timeframe in which a visitor had the CV open in one tab, with exactly one set of versions (R4.7).</summary>
public sealed class TrackSession
{
    /// <summary>Random id generated by the client (bound to the visitor on creation).</summary>
    public required string Id { get; set; }
    public Guid VisitorId { get; set; }
    public required string TenantId { get; set; }
    /// <summary>Visitor group: invite id or "public:&lt;profile&gt;".</summary>
    public required string GroupKey { get; set; }
    public Guid? InviteId { get; set; }
    public string Profile { get; set; } = "";
    public string? TabId { get; set; }
    public string? PreviousSessionId { get; set; }
    /// <summary>Chain of linked sessions (same tab, split by version change or resume, R4.6).</summary>
    public string VisitId { get; set; } = "";
    public DateTimeOffset StartedAt { get; set; }
    public DateTimeOffset LastSeenAt { get; set; }
    public DateTimeOffset? EndedAt { get; set; }
    public string? EndReason { get; set; }
    public long VisibleMs { get; set; }
    public long ActiveMs { get; set; }
    public int MaxScroll { get; set; }
    public int LastSeq { get; set; } = -1;
    public string? Locale { get; set; }
    public string? Breakpoint { get; set; }
    public int? ViewportW { get; set; }
    public int? ViewportH { get; set; }
    public string? Referrer { get; set; }
    public int? LocalHour { get; set; }
    public string? ColorScheme { get; set; }
    /// <summary>DNT / GPC signals present ("dnt,gpc").</summary>
    public string? Signals { get; set; }

    // Network (§3.2): IP truncated and fingerprint removed after the retention period (R9.2).
    public string? Ip { get; set; }
    /// <summary>Network of the IP (/24 for IPv4, /48 for IPv6), used to link fingerprints (R3.10).</summary>
    public string? IpNet { get; set; }
    public bool IpTruncated { get; set; }
    public string? IpCountry { get; set; }
    public string? IpRegion { get; set; }
    public string? IpCity { get; set; }
    public long? Asn { get; set; }
    public string? AsOrg { get; set; }
    public string? Fp { get; set; }
    public string? FpPartsJson { get; set; }
    public string? FpServer { get; set; }

    // Versions (§6.4).
    public string? AppSha { get; set; }
    public string? ApiSha { get; set; }
    public string? CvSourceSha { get; set; }
    public string? CvVersion { get; set; }
    public bool VersionMismatch { get; set; }

    public DateTimeOffset EndOrLast => EndedAt ?? LastSeenAt;
}

public sealed class SessionIp
{
    public long Id { get; set; }
    public required string SessionId { get; set; }
    public required string Ip { get; set; }
    public DateTimeOffset FirstSeen { get; set; }
    public DateTimeOffset LastSeen { get; set; }
}

/// <summary>Raw semantic event of a session (clicks, tech filter, PDF, …); cursor samples go to heat cells only.</summary>
public sealed class TrackEvent
{
    public long Id { get; set; }
    public required string SessionId { get; set; }
    public int Seq { get; set; }
    /// <summary>Milliseconds since session start.</summary>
    public long T { get; set; }
    public required string Type { get; set; }
    public string? Anchor { get; set; }
    public string? PayloadJson { get; set; }
}

/// <summary>Attention per anchor (section or entry) and session.</summary>
public sealed class SectionStat
{
    public required string SessionId { get; set; }
    public required string Anchor { get; set; }
    public long VisibleMs { get; set; }
    public int Views { get; set; }
    public long HoverMs { get; set; }
    public int Clicks { get; set; }
}

/// <summary>Aggregated heatmap cell (1 % grid inside an anchor), keyed by group, breakpoint and versions (R6.7).</summary>
public sealed class HeatCell
{
    public required string TenantId { get; set; }
    public required string GroupKey { get; set; }
    public required string Breakpoint { get; set; }
    public required string AppSha { get; set; }
    public required string CvVersion { get; set; }
    /// <summary>"move" or "click".</summary>
    public required string Type { get; set; }
    public required string Anchor { get; set; }
    public int Cx { get; set; }
    public int Cy { get; set; }
    public long Weight { get; set; }
    public DateTimeOffset LastAt { get; set; }
}

/// <summary>Redacted CV exactly as delivered, once per version (R6.12).</summary>
public sealed class CvSnapshot
{
    public required string TenantId { get; set; }
    public required string CvVersion { get; set; }
    public required string Locale { get; set; }
    public string? CvSourceSha { get; set; }
    public required string Json { get; set; }
    public DateTimeOffset FirstSeen { get; set; }
    public DateTimeOffset LastUsed { get; set; }
}

/// <summary>Consent log (R9.10): the decision only, never linked to a visitor on decline.</summary>
public sealed class ConsentRecord
{
    public long Id { get; set; }
    public required string TenantId { get; set; }
    public Guid? InviteId { get; set; }
    public required string GroupKey { get; set; }
    public Guid? VisitorId { get; set; }
    /// <summary>accept | decline | withdraw</summary>
    public required string Choice { get; set; }
    /// <summary>modal | footer | dnt | gpc</summary>
    public required string Source { get; set; }
    public string? Signals { get; set; }
    public required string PolicyVersion { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
}

public sealed class TrackingDbContext(DbContextOptions<TrackingDbContext> options) : DbContext(options)
{
    public DbSet<Visitor> Visitors => Set<Visitor>();
    public DbSet<Person> Persons => Set<Person>();
    public DbSet<TrackSession> Sessions => Set<TrackSession>();
    public DbSet<SessionIp> SessionIps => Set<SessionIp>();
    public DbSet<TrackEvent> Events => Set<TrackEvent>();
    public DbSet<SectionStat> SectionStats => Set<SectionStat>();
    public DbSet<HeatCell> HeatCells => Set<HeatCell>();
    public DbSet<CvSnapshot> CvSnapshots => Set<CvSnapshot>();
    public DbSet<ConsentRecord> Consents => Set<ConsentRecord>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        b.Entity<Visitor>().HasIndex(v => new { v.TenantId, v.PersonId });
        b.Entity<Person>().HasIndex(p => p.TenantId);
        var session = b.Entity<TrackSession>();
        session.HasIndex(s => new { s.TenantId, s.GroupKey });
        session.HasIndex(s => s.VisitorId);
        session.HasIndex(s => new { s.TenantId, s.IpNet });
        session.Ignore(s => s.EndOrLast);
        b.Entity<SessionIp>().HasIndex(i => i.SessionId);
        b.Entity<TrackEvent>().HasIndex(e => e.SessionId);
        b.Entity<SectionStat>().HasKey(s => new { s.SessionId, s.Anchor });
        b.Entity<HeatCell>().HasKey(c => new { c.TenantId, c.GroupKey, c.Breakpoint, c.AppSha, c.CvVersion, c.Type, c.Anchor, c.Cx, c.Cy });
        b.Entity<CvSnapshot>().HasKey(s => new { s.TenantId, s.CvVersion });
        b.Entity<ConsentRecord>().HasIndex(c => new { c.TenantId, c.GroupKey });

        // SQLite cannot order/compare DateTimeOffset natively; store as UTC ticks (as in app.db).
        var converter = new Microsoft.EntityFrameworkCore.Storage.ValueConversion.DateTimeOffsetToBinaryConverter();
        foreach (var property in b.Model.GetEntityTypes().SelectMany(t => t.GetProperties())
                     .Where(p => p.ClrType == typeof(DateTimeOffset) || p.ClrType == typeof(DateTimeOffset?)))
            property.SetValueConverter(converter);
    }
}
