name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: nuxt-cv:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run -d --name test-container -p 3000:3000 nuxt-cv:test
          sleep 10
          
          # Test that the server is responding
          curl -f http://localhost:3000 || (docker logs test-container && exit 1)
          
          # Clean up
          docker stop test-container
          docker rm test-container

      - name: Test Docker Compose
        run: |
          docker compose up -d
          sleep 10
          
          # Test that the server is responding
          curl -f http://localhost:3000 || (docker compose logs && exit 1)
          
          # Clean up
          docker compose down
